import type { LearningCard } from '../learningCards/types';

export type LiteracyItem = LearningCard;

export const LITERACY_ITEMS: LiteracyItem[] = [
  {
    id: 'ren',
    glyph: '人',
    title: '人',
    phonetic: 'rén',
    graphic: '🧍',
    imageLabel: '人',
    words: [
      { text: '大人', pinyin: 'dà rén' },
      { text: '小人', pinyin: 'xiǎo rén' },
      { text: '家人', pinyin: 'jiā rén' },
    ],
    sentence: '人会走路，也会说话。',
    tone: 'from-amber-100 via-lime-100 to-emerald-100',
  },
  {
    id: 'kou',
    glyph: '口',
    title: '口',
    phonetic: 'kǒu',
    graphic: '👄',
    imageLabel: '嘴巴',
    words: [
      { text: '人口', pinyin: 'rén kǒu' },
      { text: '门口', pinyin: 'mén kǒu' },
      { text: '一口', pinyin: 'yì kǒu' },
    ],
    sentence: '口可以说话，也可以吃东西。',
    tone: 'from-rose-100 via-orange-100 to-yellow-100',
  },
  {
    id: 'shou',
    glyph: '手',
    title: '手',
    phonetic: 'shǒu',
    graphic: '✋',
    imageLabel: '小手',
    words: [
      { text: '小手', pinyin: 'xiǎo shǒu' },
      { text: '拍手', pinyin: 'pāi shǒu' },
      { text: '洗手', pinyin: 'xǐ shǒu' },
    ],
    sentence: '手可以拿东西，也可以拍拍手。',
    tone: 'from-sky-100 via-cyan-100 to-emerald-100',
  },
  {
    id: 'ri',
    glyph: '日',
    title: '日',
    phonetic: 'rì',
    graphic: '☀️',
    imageLabel: '太阳',
    words: [
      { text: '日子', pinyin: 'rì zi' },
      { text: '生日', pinyin: 'shēng rì' },
      { text: '今日', pinyin: 'jīn rì' },
    ],
    sentence: '太阳出来，是亮亮的一日。',
    tone: 'from-yellow-100 via-amber-100 to-lime-100',
  },
  {
    id: 'yue',
    glyph: '月',
    title: '月',
    phonetic: 'yuè',
    graphic: '🌙',
    imageLabel: '月亮',
    words: [
      { text: '月亮', pinyin: 'yuè liang' },
      { text: '一月', pinyin: 'yī yuè' },
      { text: '月牙', pinyin: 'yuè yá' },
    ],
    sentence: '晚上抬头，可以看到月亮。',
    tone: 'from-indigo-100 via-sky-100 to-cyan-100',
  },
  {
    id: 'shan',
    glyph: '山',
    title: '山',
    phonetic: 'shān',
    graphic: '⛰️',
    imageLabel: '大山',
    words: [
      { text: '大山', pinyin: 'dà shān' },
      { text: '山上', pinyin: 'shān shàng' },
      { text: '山水', pinyin: 'shān shuǐ' },
    ],
    sentence: '山高高的，像站起来的线条。',
    tone: 'from-emerald-100 via-lime-100 to-teal-100',
  },
  {
    id: 'shui',
    glyph: '水',
    title: '水',
    phonetic: 'shuǐ',
    graphic: '💧',
    imageLabel: '水滴',
    words: [
      { text: '喝水', pinyin: 'hē shuǐ' },
      { text: '水果', pinyin: 'shuǐ guǒ' },
      { text: '山水', pinyin: 'shān shuǐ' },
    ],
    sentence: '水会流，也能让小树长大。',
    tone: 'from-cyan-100 via-sky-100 to-emerald-100',
  },
  {
    id: 'huo',
    glyph: '火',
    title: '火',
    phonetic: 'huǒ',
    graphic: '🔥',
    imageLabel: '火苗',
    words: [
      { text: '火苗', pinyin: 'huǒ miáo' },
      { text: '火山', pinyin: 'huǒ shān' },
      { text: '大火', pinyin: 'dà huǒ' },
    ],
    sentence: '火很亮，也很热，要远远看。',
    tone: 'from-orange-100 via-rose-100 to-yellow-100',
  },
  {
    id: 'mu',
    glyph: '木',
    title: '木',
    phonetic: 'mù',
    graphic: '🌳',
    imageLabel: '树木',
    words: [
      { text: '木头', pinyin: 'mù tou' },
      { text: '树木', pinyin: 'shù mù' },
      { text: '木马', pinyin: 'mù mǎ' },
    ],
    sentence: '一棵树，也可以叫一木。',
    tone: 'from-lime-100 via-green-100 to-emerald-100',
  },
  {
    id: 'tian',
    glyph: '田',
    title: '田',
    phonetic: 'tián',
    graphic: '🌾',
    imageLabel: '田地',
    words: [
      { text: '田地', pinyin: 'tián dì' },
      { text: '水田', pinyin: 'shuǐ tián' },
      { text: '田里', pinyin: 'tián lǐ' },
    ],
    sentence: '田里可以种出粮食。',
    tone: 'from-yellow-100 via-lime-100 to-green-100',
  },
  {
    id: 'yu',
    glyph: '雨',
    title: '雨',
    phonetic: 'yǔ',
    graphic: '🌧️',
    imageLabel: '下雨',
    words: [
      { text: '下雨', pinyin: 'xià yǔ' },
      { text: '雨衣', pinyin: 'yǔ yī' },
      { text: '雨点', pinyin: 'yǔ diǎn' },
    ],
    sentence: '雨点落下来，小草喝到水。',
    tone: 'from-slate-100 via-sky-100 to-cyan-100',
  },
  {
    id: 'hua',
    glyph: '花',
    title: '花',
    phonetic: 'huā',
    graphic: '🌸',
    imageLabel: '小花',
    words: [
      { text: '小花', pinyin: 'xiǎo huā' },
      { text: '花朵', pinyin: 'huā duǒ' },
      { text: '开花', pinyin: 'kāi huā' },
    ],
    sentence: '花开了，颜色很漂亮。',
    tone: 'from-pink-100 via-rose-100 to-lime-100',
  },
  {
    id: 'cao',
    glyph: '草',
    title: '草',
    phonetic: 'cǎo',
    graphic: '🌱',
    imageLabel: '小草',
    words: [
      { text: '小草', pinyin: 'xiǎo cǎo' },
      { text: '草地', pinyin: 'cǎo dì' },
      { text: '青草', pinyin: 'qīng cǎo' },
    ],
    sentence: '雨后的小草绿绿的。',
    tone: 'from-lime-100 via-emerald-100 to-sky-100',
  },
  {
    id: 'niao',
    glyph: '鸟',
    title: '鸟',
    phonetic: 'niǎo',
    graphic: '🐦',
    imageLabel: '小鸟',
    words: [
      { text: '小鸟', pinyin: 'xiǎo niǎo' },
      { text: '鸟叫', pinyin: 'niǎo jiào' },
      { text: '飞鸟', pinyin: 'fēi niǎo' },
    ],
    sentence: '小鸟在树上唱歌。',
    tone: 'from-sky-100 via-cyan-100 to-lime-100',
  },
  {
    id: 'yu-fish',
    glyph: '鱼',
    title: '鱼',
    phonetic: 'yú',
    graphic: '🐟',
    imageLabel: '小鱼',
    words: [
      { text: '小鱼', pinyin: 'xiǎo yú' },
      { text: '鱼水', pinyin: 'yú shuǐ' },
      { text: '金鱼', pinyin: 'jīn yú' },
    ],
    sentence: '小鱼在水里游来游去。',
    tone: 'from-cyan-100 via-sky-100 to-teal-100',
  },
  {
    id: 'ma',
    glyph: '马',
    title: '马',
    phonetic: 'mǎ',
    graphic: '🐴',
    imageLabel: '小马',
    words: [
      { text: '小马', pinyin: 'xiǎo mǎ' },
      { text: '木马', pinyin: 'mù mǎ' },
      { text: '马车', pinyin: 'mǎ chē' },
    ],
    sentence: '小马跑得很快。',
    tone: 'from-amber-100 via-orange-100 to-lime-100',
  },
  {
    id: 'niu',
    glyph: '牛',
    title: '牛',
    phonetic: 'niú',
    graphic: '🐮',
    imageLabel: '小牛',
    words: [
      { text: '小牛', pinyin: 'xiǎo niú' },
      { text: '牛奶', pinyin: 'niú nǎi' },
      { text: '水牛', pinyin: 'shuǐ niú' },
    ],
    sentence: '小牛低头吃青草。',
    tone: 'from-stone-100 via-yellow-100 to-lime-100',
  },
  {
    id: 'yang',
    glyph: '羊',
    title: '羊',
    phonetic: 'yáng',
    graphic: '🐑',
    imageLabel: '小羊',
    words: [
      { text: '小羊', pinyin: 'xiǎo yáng' },
      { text: '山羊', pinyin: 'shān yáng' },
      { text: '羊毛', pinyin: 'yáng máo' },
    ],
    sentence: '小羊的毛软软的。',
    tone: 'from-slate-100 via-lime-100 to-emerald-100',
  },
  {
    id: 'che',
    glyph: '车',
    title: '车',
    phonetic: 'chē',
    graphic: '🚗',
    imageLabel: '小车',
    words: [
      { text: '小车', pinyin: 'xiǎo chē' },
      { text: '火车', pinyin: 'huǒ chē' },
      { text: '车门', pinyin: 'chē mén' },
    ],
    sentence: '车轮转起来，车就向前走。',
    tone: 'from-red-100 via-orange-100 to-yellow-100',
  },
  {
    id: 'men',
    glyph: '门',
    title: '门',
    phonetic: 'mén',
    graphic: '🚪',
    imageLabel: '门',
    words: [
      { text: '大门', pinyin: 'dà mén' },
      { text: '门口', pinyin: 'mén kǒu' },
      { text: '开门', pinyin: 'kāi mén' },
    ],
    sentence: '轻轻开门，回到家里。',
    tone: 'from-amber-100 via-stone-100 to-sky-100',
  },
  {
    id: 'xin',
    glyph: '心',
    title: '心',
    phonetic: 'xīn',
    graphic: '❤️',
    imageLabel: '爱心',
    words: [
      { text: '爱心', pinyin: 'ài xīn' },
      { text: '开心', pinyin: 'kāi xīn' },
      { text: '小心', pinyin: 'xiǎo xīn' },
    ],
    sentence: '开心的时候，心里暖暖的。',
    tone: 'from-pink-100 via-rose-100 to-orange-100',
  },
  {
    id: 'xing',
    glyph: '星',
    title: '星',
    phonetic: 'xīng',
    graphic: '⭐',
    imageLabel: '星星',
    words: [
      { text: '星星', pinyin: 'xīng xing' },
      { text: '火星', pinyin: 'huǒ xīng' },
      { text: '星空', pinyin: 'xīng kōng' },
    ],
    sentence: '夜晚的星星一闪一闪。',
    tone: 'from-indigo-100 via-sky-100 to-yellow-100',
  },
  {
    id: 'yun',
    glyph: '云',
    title: '云',
    phonetic: 'yún',
    graphic: '☁️',
    imageLabel: '白云',
    words: [
      { text: '白云', pinyin: 'bái yún' },
      { text: '云朵', pinyin: 'yún duǒ' },
      { text: '云山', pinyin: 'yún shān' },
    ],
    sentence: '白云慢慢飘过天空。',
    tone: 'from-sky-100 via-blue-100 to-white',
  },
  {
    id: 'guo',
    glyph: '果',
    title: '果',
    phonetic: 'guǒ',
    graphic: '🍎',
    imageLabel: '果子',
    words: [
      { text: '果子', pinyin: 'guǒ zi' },
      { text: '水果', pinyin: 'shuǐ guǒ' },
      { text: '苹果', pinyin: 'píng guǒ' },
    ],
    sentence: '树上结出了红红的果子。',
    tone: 'from-red-100 via-yellow-100 to-lime-100',
  },
];

export const DEFAULT_LITERACY_ITEM = LITERACY_ITEMS[0];

export function findLiteracyItemById(id: string | null | undefined) {
  return LITERACY_ITEMS.find((item) => item.id === id) ?? null;
}
