import type {
  Block,
  CommandKind,
  Procedures,
  ProgrammingDirection,
  ProgrammingPosition,
} from './engine/types';
import type { StarThresholds } from './engine/starEvaluator';
import type { ProgrammingBlockTemplateId } from './blocks';

export type { ProgrammingDirection, ProgrammingPosition };

export type ProgrammingWorldId =
  | 'forest'
  | 'meadow'
  | 'cave'
  | 'canyon'
  | 'tower';

export interface ProgrammingLevel {
  id: string;
  title: string;
  concept: string;
  worldId: ProgrammingWorldId;
  difficultyStars: 1 | 2 | 3 | 4 | 5;
  conceptTags: CommandKind[];
  isChallenge?: boolean;
  isBoss?: boolean;
  prompt: string;
  guide: string;
  successVoice: string;
  hintVoice: string;
  start: ProgrammingPosition;
  direction: ProgrammingDirection;
  target: ProgrammingPosition;
  obstacles: ProgrammingPosition[];
  gems?: ProgrammingPosition[];
  requiresAllGems?: boolean;
  width?: number;
  height?: number;
  allowedCommands: ProgrammingBlockTemplateId[];
  maxCommands: number;
  requiredKinds?: CommandKind[];
  requiredCommandMessage?: string;
  optimalSteps?: number;
  starThresholds?: StarThresholds;
  procedures?: Procedures;
  defaultProcedureId?: string;
  sampleProgram: Block[];
}

export const PROGRAMMING_LEVELS: ProgrammingLevel[] = [
  {
    id: 'sequence-apple',
    title: '第一条小路',
    concept: '顺序',
    worldId: 'forest',
    difficultyStars: 1,
    conceptTags: ['forward'],
    prompt: '让小满一步一步走到能量果。',
    guide: '先从最简单的顺序开始。每点一次前进，小满就往前走一格。',
    successVoice: '走到啦。你把三步按对了，这就是顺序。',
    hintVoice: '小满还没到果子。数一数，中间还差几格。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 3, y: 4 },
    obstacles: [],
    allowedCommands: ['forward'],
    maxCommands: 5,
    optimalSteps: 3,
    starThresholds: { threeStarsMaxSteps: 3, twoStarsMaxSteps: 4, oneStarMaxSteps: 5 },
    sampleProgram: [
      { id: 'sample-0', kind: 'forward' },
      { id: 'sample-1', kind: 'forward' },
      { id: 'sample-2', kind: 'forward' },
    ],
  },
  {
    id: 'turn-corner',
    title: '拐个小弯',
    concept: '转向',
    worldId: 'forest',
    difficultyStars: 1,
    conceptTags: ['forward', 'turnLeft'],
    prompt: '先走到转角，再转向上面。',
    guide: '这次要用转向。转向不会移动，只会让小满换一个朝向。',
    successVoice: '很好。你先走，再转向，再继续走，小满听懂了。',
    hintVoice: '想一想，转向这一步要放在走到转角以后。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 2, y: 2 },
    obstacles: [],
    allowedCommands: ['forward', 'turnLeft', 'turnRight'],
    maxCommands: 7,
    optimalSteps: 5,
    starThresholds: { threeStarsMaxSteps: 5, twoStarsMaxSteps: 6, oneStarMaxSteps: 7 },
    sampleProgram: [
      { id: 'sample-0', kind: 'forward' },
      { id: 'sample-1', kind: 'forward' },
      { id: 'sample-2', kind: 'turnLeft' },
      { id: 'sample-3', kind: 'forward' },
      { id: 'sample-4', kind: 'forward' },
    ],
  },
  {
    id: 'debug-rocks',
    title: '绕开石头',
    concept: '调试',
    worldId: 'forest',
    difficultyStars: 2,
    conceptTags: ['forward', 'turnLeft', 'turnRight'],
    prompt: '路上有石头，帮小满绕过去。',
    guide: '如果撞到石头，就换一条路。编程里这叫调试。',
    successVoice: '漂亮。你绕开了石头，也修好了路线。',
    hintVoice: '前面被石头挡住了。先让小满往没有石头的格子走。',
    start: { x: 0, y: 3 },
    direction: 'east',
    target: { x: 4, y: 1 },
    obstacles: [
      { x: 2, y: 3 },
      { x: 2, y: 2 },
      { x: 3, y: 2 },
    ],
    allowedCommands: ['forward', 'turnLeft', 'turnRight'],
    maxCommands: 10,
    optimalSteps: 8,
    starThresholds: { threeStarsMaxSteps: 8, twoStarsMaxSteps: 9, oneStarMaxSteps: 10 },
    sampleProgram: [
      { id: 'sample-0', kind: 'forward' },
      { id: 'sample-1', kind: 'turnLeft' },
      { id: 'sample-2', kind: 'forward' },
      { id: 'sample-3', kind: 'forward' },
      { id: 'sample-4', kind: 'turnRight' },
      { id: 'sample-5', kind: 'forward' },
      { id: 'sample-6', kind: 'forward' },
      { id: 'sample-7', kind: 'forward' },
    ],
  },
  {
    id: 'repeat-bridge',
    title: '重复四步',
    concept: '重复',
    worldId: 'forest',
    difficultyStars: 2,
    conceptTags: ['repeat', 'forward'],
    prompt: '用重复，让小满一口气走过长桥。',
    guide: '重复块会把里面的动作多做几次。相同动作出现很多次，就可以试试重复。',
    successVoice: '对啦。一次重复就走完长桥了。',
    hintVoice: '这里是一条直直的路。试试把前进放进重复里。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 4, y: 4 },
    obstacles: [],
    allowedCommands: ['forward', 'repeat'],
    maxCommands: 4,
    requiredKinds: ['repeat'],
    requiredCommandMessage: '这关要试一次重复。把前进放进重复块，再运行看看。',
    optimalSteps: 4,
    starThresholds: { threeStarsMaxSteps: 4, twoStarsMaxSteps: 5, oneStarMaxSteps: 6 },
    sampleProgram: [
      {
        id: 'sample-repeat',
        kind: 'repeat',
        params: { n: 4 },
        body: [{ id: 'sample-repeat:body.0', kind: 'forward' }],
      },
    ],
  },
  {
    id: 'ifpath-stone-gate',
    title: '有路才走',
    concept: '条件',
    worldId: 'forest',
    difficultyStars: 2,
    conceptTags: ['ifPath', 'forward', 'turnLeft'],
    isBoss: true,
    prompt: '前面堵住时，先判断有没有路。',
    guide: '如果前面有路，就继续走；如果没路，就先转向。',
    successVoice: '判断成功。小满没有撞上石头。',
    hintVoice: '前面有石头。用“如果有路”让小满先换方向。',
    start: { x: 0, y: 2 },
    direction: 'east',
    target: { x: 2, y: 1 },
    obstacles: [{ x: 1, y: 2 }],
    allowedCommands: ['ifPath', 'forward', 'turnLeft', 'turnRight'],
    maxCommands: 6,
    requiredKinds: ['ifPath'],
    requiredCommandMessage: '这关要用“如果有路”。让小满先判断，再继续走。',
    optimalSteps: 5,
    starThresholds: { threeStarsMaxSteps: 5, twoStarsMaxSteps: 6, oneStarMaxSteps: 7 },
    sampleProgram: [
      {
        id: 'sample-ifpath',
        kind: 'ifPath',
        branchTrue: [{ id: 'sample-ifpath:true.0', kind: 'forward' }],
        branchFalse: [{ id: 'sample-ifpath:false.0', kind: 'turnLeft' }],
      },
      { id: 'sample-1', kind: 'forward' },
      { id: 'sample-2', kind: 'turnRight' },
      { id: 'sample-3', kind: 'forward' },
      { id: 'sample-4', kind: 'forward' },
    ],
  },
  {
    id: 'collect-first-star',
    title: '捡起能量星',
    concept: '收集',
    worldId: 'meadow',
    difficultyStars: 2,
    conceptTags: ['collect', 'forward'],
    prompt: '先拿到能量星，再走到终点。',
    guide: '小满站在能量星上时，用收集块把它装进口袋。',
    successVoice: '能量星收好啦。你完成了收集任务。',
    hintVoice: '要站到星星格子上，再放一个收集块。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 2, y: 4 },
    obstacles: [],
    gems: [{ x: 1, y: 4 }],
    requiresAllGems: true,
    allowedCommands: ['forward', 'collect'],
    maxCommands: 4,
    requiredKinds: ['collect'],
    requiredCommandMessage: '这关要收集能量星。站到星星上以后点收集。',
    optimalSteps: 3,
    starThresholds: { threeStarsMaxSteps: 3, twoStarsMaxSteps: 4, oneStarMaxSteps: 5 },
    sampleProgram: [
      { id: 'sample-0', kind: 'forward' },
      { id: 'sample-1', kind: 'collect' },
      { id: 'sample-2', kind: 'forward' },
    ],
  },
  {
    id: 'ifgem-pouch',
    title: '看到星星就收',
    concept: '条件收集',
    worldId: 'meadow',
    difficultyStars: 3,
    conceptTags: ['ifGem', 'collect', 'forward'],
    prompt: '用“如果有星”，让小满自己决定要不要收集。',
    guide: '条件不只会看路，也可以看看脚下有没有能量星。',
    successVoice: '太好了。小满会看见星星再收集。',
    hintVoice: '先走到星星上，再放“如果有星”。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 3, y: 4 },
    obstacles: [],
    gems: [{ x: 1, y: 4 }],
    requiresAllGems: true,
    allowedCommands: ['forward', 'ifGem', 'collect'],
    maxCommands: 5,
    requiredKinds: ['ifGem'],
    requiredCommandMessage: '这关要用“如果有星”，让收集动作藏在条件里。',
    optimalSteps: 4,
    starThresholds: { threeStarsMaxSteps: 4, twoStarsMaxSteps: 5, oneStarMaxSteps: 6 },
    sampleProgram: [
      { id: 'sample-0', kind: 'forward' },
      {
        id: 'sample-ifgem',
        kind: 'ifGem',
        branchTrue: [{ id: 'sample-ifgem:true.0', kind: 'collect' }],
        branchFalse: [{ id: 'sample-ifgem:false.0', kind: 'forward' }],
      },
      { id: 'sample-2', kind: 'forward' },
      { id: 'sample-3', kind: 'forward' },
    ],
  },
  {
    id: 'while-runway',
    title: '一直走到终点',
    concept: '循环',
    worldId: 'cave',
    difficultyStars: 3,
    conceptTags: ['whileNotGoal', 'forward'],
    prompt: '用“直到终点”，让小满自己重复前进。',
    guide: '只要还没到终点，就一直做里面的动作。这是循环。',
    successVoice: '循环跑起来了。小满一直走到了终点。',
    hintVoice: '把前进放在“直到终点”里面。',
    start: { x: 0, y: 0 },
    direction: 'east',
    target: { x: 4, y: 0 },
    obstacles: [],
    allowedCommands: ['whileNotGoal', 'forward'],
    maxCommands: 3,
    requiredKinds: ['whileNotGoal'],
    requiredCommandMessage: '这关要用“直到终点”。它会一直运行里面的前进。',
    optimalSteps: 4,
    starThresholds: { threeStarsMaxSteps: 4, twoStarsMaxSteps: 5, oneStarMaxSteps: 6 },
    sampleProgram: [
      {
        id: 'sample-while',
        kind: 'whileNotGoal',
        body: [{ id: 'sample-while:body.0', kind: 'forward' }],
      },
    ],
  },
  {
    id: 'jump-rocks',
    title: '跳过石头',
    concept: '跳跃',
    worldId: 'canyon',
    difficultyStars: 3,
    conceptTags: ['jump', 'forward'],
    prompt: '石头挡住小路，试试跳过去。',
    guide: '跳跃会向前跳两格，可以越过一格石头。',
    successVoice: '跳过去了。小满落在安全格子上。',
    hintVoice: '普通前进会撞石头，这里需要跳跃。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 4, y: 4 },
    obstacles: [
      { x: 1, y: 4 },
      { x: 3, y: 4 },
    ],
    allowedCommands: ['jump', 'forward'],
    maxCommands: 4,
    requiredKinds: ['jump'],
    requiredCommandMessage: '这关要用跳跃，越过挡路的石头。',
    optimalSteps: 2,
    starThresholds: { threeStarsMaxSteps: 2, twoStarsMaxSteps: 3, oneStarMaxSteps: 4 },
    sampleProgram: [
      { id: 'sample-0', kind: 'jump' },
      { id: 'sample-1', kind: 'jump' },
    ],
  },
  {
    id: 'procedure-stairs',
    title: '调用小路',
    concept: '过程',
    worldId: 'tower',
    difficultyStars: 3,
    conceptTags: ['procCall', 'forward', 'turnLeft'],
    prompt: '把一段常用路线装成“小路”，需要时调用它。',
    guide: '过程就像一张小路线卡。调用它，小满会照着整段路线走。',
    successVoice: '调用成功。小满照着小路卡走到了终点。',
    hintVoice: '试试调用小路，它已经放好了完整路线。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 2, y: 2 },
    obstacles: [],
    allowedCommands: ['procCall', 'forward', 'turnLeft'],
    maxCommands: 4,
    requiredKinds: ['procCall'],
    requiredCommandMessage: '这关要用“调用小路”。它会运行预设的路线。',
    procedures: {
      helper: [
        { id: 'helper-0', kind: 'forward' },
        { id: 'helper-1', kind: 'forward' },
        { id: 'helper-2', kind: 'turnLeft' },
        { id: 'helper-3', kind: 'forward' },
        { id: 'helper-4', kind: 'forward' },
      ],
    },
    defaultProcedureId: 'helper',
    optimalSteps: 5,
    starThresholds: { threeStarsMaxSteps: 5, twoStarsMaxSteps: 6, oneStarMaxSteps: 7 },
    sampleProgram: [
      { id: 'sample-proc', kind: 'procCall', params: { procedureId: 'helper' } },
    ],
  },
  {
    id: 'collect-two-stars',
    title: '两颗能量星',
    concept: '连续收集',
    worldId: 'meadow',
    difficultyStars: 3,
    conceptTags: ['collect', 'forward'],
    prompt: '沿着草地拿到两颗能量星，再到终点。',
    guide: '走到星星上就收集，收好以后继续前进。',
    successVoice: '两颗星都收好啦。',
    hintVoice: '每到一颗星星上，都要放一个收集块。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 4, y: 4 },
    obstacles: [],
    gems: [
      { x: 1, y: 4 },
      { x: 3, y: 4 },
    ],
    requiresAllGems: true,
    allowedCommands: ['forward', 'collect'],
    maxCommands: 7,
    requiredKinds: ['collect'],
    requiredCommandMessage: '这关要把两颗能量星都收集起来。',
    optimalSteps: 6,
    starThresholds: { threeStarsMaxSteps: 6, twoStarsMaxSteps: 7, oneStarMaxSteps: 8 },
    sampleProgram: [
      { id: 'sample-0', kind: 'forward' },
      { id: 'sample-1', kind: 'collect' },
      { id: 'sample-2', kind: 'forward' },
      { id: 'sample-3', kind: 'forward' },
      { id: 'sample-4', kind: 'collect' },
      { id: 'sample-5', kind: 'forward' },
    ],
  },
  {
    id: 'corner-star',
    title: '角落星星',
    concept: '转向收集',
    worldId: 'meadow',
    difficultyStars: 3,
    conceptTags: ['collect', 'turnLeft', 'forward'],
    prompt: '先拿角落的星星，再上楼梯到终点。',
    guide: '收集任务也可以和转向组合在一起。',
    successVoice: '你先收星星，再转向到了终点。',
    hintVoice: '星星在横路上，终点在上面。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 2, y: 2 },
    obstacles: [],
    gems: [{ x: 2, y: 4 }],
    requiresAllGems: true,
    allowedCommands: ['forward', 'turnLeft', 'collect'],
    maxCommands: 7,
    requiredKinds: ['collect'],
    requiredCommandMessage: '先走到星星上收集，再去终点。',
    optimalSteps: 5,
    starThresholds: { threeStarsMaxSteps: 5, twoStarsMaxSteps: 6, oneStarMaxSteps: 7 },
    sampleProgram: [
      { id: 'sample-0', kind: 'forward' },
      { id: 'sample-1', kind: 'forward' },
      { id: 'sample-2', kind: 'collect' },
      { id: 'sample-3', kind: 'turnLeft' },
      { id: 'sample-4', kind: 'forward' },
      { id: 'sample-5', kind: 'forward' },
    ],
  },
  {
    id: 'ifgem-empty-path',
    title: '有星才收',
    concept: '条件判断',
    worldId: 'meadow',
    difficultyStars: 3,
    conceptTags: ['ifGem', 'collect', 'forward'],
    prompt: '有星星时收集，没有星星时继续走。',
    guide: '如果有星块会先看脚下有没有星星，再选择里面的动作。',
    successVoice: '小满会自己判断有没有星星了。',
    hintVoice: '第一格没有星星，可以让“否”分支继续前进。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 4, y: 4 },
    obstacles: [],
    gems: [{ x: 2, y: 4 }],
    requiresAllGems: true,
    allowedCommands: ['forward', 'ifGem', 'collect'],
    maxCommands: 6,
    requiredKinds: ['ifGem'],
    requiredCommandMessage: '这关要用“如果有星”来做判断。',
    optimalSteps: 5,
    starThresholds: { threeStarsMaxSteps: 5, twoStarsMaxSteps: 6, oneStarMaxSteps: 7 },
    sampleProgram: [
      { id: 'sample-0', kind: 'forward' },
      {
        id: 'sample-ifgem-0',
        kind: 'ifGem',
        branchTrue: [{ id: 'sample-ifgem-0:true.0', kind: 'collect' }],
        branchFalse: [{ id: 'sample-ifgem-0:false.0', kind: 'forward' }],
      },
      {
        id: 'sample-ifgem-1',
        kind: 'ifGem',
        branchTrue: [{ id: 'sample-ifgem-1:true.0', kind: 'collect' }],
        branchFalse: [{ id: 'sample-ifgem-1:false.0', kind: 'forward' }],
      },
      { id: 'sample-3', kind: 'forward' },
      { id: 'sample-4', kind: 'forward' },
    ],
  },
  {
    id: 'repeat-collect-row',
    title: '重复收星',
    concept: '重复收集',
    worldId: 'meadow',
    difficultyStars: 4,
    conceptTags: ['repeat', 'collect', 'forward'],
    prompt: '用重复块收两颗排成一排的星星。',
    guide: '前进和收集这两个动作会重复出现，适合放进重复块。',
    successVoice: '重复收集成功。',
    hintVoice: '把前进和收集都放进重复块里。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 3, y: 4 },
    obstacles: [],
    gems: [
      { x: 1, y: 4 },
      { x: 2, y: 4 },
    ],
    requiresAllGems: true,
    allowedCommands: ['forward', 'collect', 'repeat'],
    maxCommands: 4,
    requiredKinds: ['repeat', 'collect'],
    requiredCommandMessage: '这关要用重复来完成连续收集。',
    optimalSteps: 5,
    starThresholds: { threeStarsMaxSteps: 5, twoStarsMaxSteps: 6, oneStarMaxSteps: 7 },
    sampleProgram: [
      {
        id: 'sample-repeat',
        kind: 'repeat',
        params: { n: 2 },
        body: [
          { id: 'sample-repeat:body.0', kind: 'forward' },
          { id: 'sample-repeat:body.1', kind: 'collect' },
        ],
      },
      { id: 'sample-1', kind: 'forward' },
    ],
  },
  {
    id: 'meadow-boss',
    title: '星星草地挑战',
    concept: '收集挑战',
    worldId: 'meadow',
    difficultyStars: 4,
    conceptTags: ['collect', 'turnLeft', 'forward'],
    isBoss: true,
    prompt: '收好草地上的两颗星星，再到上面的终点。',
    guide: '先沿横路收集，再转向往上走。',
    successVoice: '草地挑战完成。',
    hintVoice: '第二颗星星在终点下面的横路上。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 4, y: 2 },
    obstacles: [],
    gems: [
      { x: 1, y: 4 },
      { x: 3, y: 4 },
    ],
    requiresAllGems: true,
    allowedCommands: ['forward', 'turnLeft', 'collect'],
    maxCommands: 10,
    requiredKinds: ['collect'],
    requiredCommandMessage: '这关要把两颗星星都收好。',
    optimalSteps: 8,
    starThresholds: { threeStarsMaxSteps: 8, twoStarsMaxSteps: 9, oneStarMaxSteps: 10 },
    sampleProgram: [
      { id: 'sample-0', kind: 'forward' },
      { id: 'sample-1', kind: 'collect' },
      { id: 'sample-2', kind: 'forward' },
      { id: 'sample-3', kind: 'forward' },
      { id: 'sample-4', kind: 'collect' },
      { id: 'sample-5', kind: 'forward' },
      { id: 'sample-6', kind: 'turnLeft' },
      { id: 'sample-7', kind: 'forward' },
      { id: 'sample-8', kind: 'forward' },
    ],
  },
  {
    id: 'repeat-corner-loop',
    title: '两段重复',
    concept: '重复转弯',
    worldId: 'cave',
    difficultyStars: 3,
    conceptTags: ['repeat', 'turnLeft', 'forward'],
    prompt: '两段直路都一样长，试试用两次重复。',
    guide: '先重复走横路，再转向，最后重复走竖路。',
    successVoice: '两段重复都安排好了。',
    hintVoice: '每一段都是两步，可以分别放进重复块。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 2, y: 2 },
    obstacles: [],
    allowedCommands: ['forward', 'turnLeft', 'repeat'],
    maxCommands: 5,
    requiredKinds: ['repeat'],
    requiredCommandMessage: '这关要用重复减少相同的前进。',
    optimalSteps: 5,
    starThresholds: { threeStarsMaxSteps: 5, twoStarsMaxSteps: 6, oneStarMaxSteps: 7 },
    sampleProgram: [
      {
        id: 'sample-repeat-a',
        kind: 'repeat',
        params: { n: 2 },
        body: [{ id: 'sample-repeat-a:body.0', kind: 'forward' }],
      },
      { id: 'sample-turn', kind: 'turnLeft' },
      {
        id: 'sample-repeat-b',
        kind: 'repeat',
        params: { n: 2 },
        body: [{ id: 'sample-repeat-b:body.0', kind: 'forward' }],
      },
    ],
  },
  {
    id: 'while-short-row',
    title: '循环短跑',
    concept: '直到终点',
    worldId: 'cave',
    difficultyStars: 3,
    conceptTags: ['whileNotGoal', 'forward'],
    prompt: '让小满一直走，直到到达终点。',
    guide: '这次不用数几步，循环会一直检查是否到终点。',
    successVoice: '循环短跑成功。',
    hintVoice: '把前进放进“直到终点”里面。',
    start: { x: 0, y: 1 },
    direction: 'east',
    target: { x: 4, y: 1 },
    obstacles: [],
    width: 5,
    height: 3,
    allowedCommands: ['whileNotGoal', 'forward'],
    maxCommands: 3,
    requiredKinds: ['whileNotGoal'],
    requiredCommandMessage: '这关要使用“直到终点”。',
    optimalSteps: 4,
    starThresholds: { threeStarsMaxSteps: 4, twoStarsMaxSteps: 5, oneStarMaxSteps: 6 },
    sampleProgram: [
      {
        id: 'sample-while',
        kind: 'whileNotGoal',
        body: [{ id: 'sample-while:body.0', kind: 'forward' }],
      },
    ],
  },
  {
    id: 'ifpath-corridor-turn',
    title: '洞口转身',
    concept: '条件避让',
    worldId: 'cave',
    difficultyStars: 4,
    conceptTags: ['ifPath', 'turnLeft', 'turnRight', 'forward'],
    prompt: '前面堵住时先转身，再穿过小洞。',
    guide: '如果有路块可以保护小满不撞墙。',
    successVoice: '你让小满先判断，再安全穿过小洞。',
    hintVoice: '开头前方没有路，否分支需要转向。',
    start: { x: 0, y: 2 },
    direction: 'east',
    target: { x: 1, y: 1 },
    obstacles: [{ x: 1, y: 2 }],
    width: 3,
    height: 3,
    allowedCommands: ['ifPath', 'forward', 'turnLeft', 'turnRight'],
    maxCommands: 6,
    requiredKinds: ['ifPath'],
    requiredCommandMessage: '这关要用“如果有路”避开堵住的洞口。',
    optimalSteps: 4,
    starThresholds: { threeStarsMaxSteps: 4, twoStarsMaxSteps: 5, oneStarMaxSteps: 6 },
    sampleProgram: [
      {
        id: 'sample-ifpath',
        kind: 'ifPath',
        branchTrue: [{ id: 'sample-ifpath:true.0', kind: 'forward' }],
        branchFalse: [{ id: 'sample-ifpath:false.0', kind: 'turnLeft' }],
      },
      { id: 'sample-1', kind: 'forward' },
      { id: 'sample-2', kind: 'turnRight' },
      { id: 'sample-3', kind: 'forward' },
    ],
  },
  {
    id: 'while-turn-cave',
    title: '会转弯的循环',
    concept: '循环判断',
    worldId: 'cave',
    difficultyStars: 4,
    conceptTags: ['whileNotGoal', 'ifPath', 'turnLeft', 'forward'],
    prompt: '走到边界时转向，一直循环到终点。',
    guide: '循环里面可以放条件：有路就走，没路就转向。',
    successVoice: '循环会判断路线了。',
    hintVoice: '循环里需要“如果有路”。没路时让小满左转。',
    start: { x: 0, y: 2 },
    direction: 'east',
    target: { x: 4, y: 0 },
    obstacles: [],
    width: 5,
    height: 3,
    allowedCommands: ['whileNotGoal', 'ifPath', 'forward', 'turnLeft'],
    maxCommands: 4,
    requiredKinds: ['whileNotGoal', 'ifPath'],
    requiredCommandMessage: '这关要把条件放进循环里。',
    optimalSteps: 7,
    starThresholds: { threeStarsMaxSteps: 7, twoStarsMaxSteps: 8, oneStarMaxSteps: 9 },
    sampleProgram: [
      {
        id: 'sample-while',
        kind: 'whileNotGoal',
        body: [
          {
            id: 'sample-while:body.if',
            kind: 'ifPath',
            branchTrue: [{ id: 'sample-while:body.if:true.0', kind: 'forward' }],
            branchFalse: [{ id: 'sample-while:body.if:false.0', kind: 'turnLeft' }],
          },
        ],
      },
    ],
  },
  {
    id: 'cave-boss',
    title: '循环洞穴挑战',
    concept: '循环收集',
    worldId: 'cave',
    difficultyStars: 4,
    conceptTags: ['repeat', 'collect', 'forward'],
    isBoss: true,
    prompt: '重复前进和收集，拿满三颗洞穴星。',
    guide: '前进、收集会连续出现三次。',
    successVoice: '洞穴星都收齐了。',
    hintVoice: '把前进和收集放进重复块，重复三次。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 4, y: 4 },
    obstacles: [],
    gems: [
      { x: 1, y: 4 },
      { x: 2, y: 4 },
      { x: 3, y: 4 },
    ],
    requiresAllGems: true,
    allowedCommands: ['repeat', 'forward', 'collect'],
    maxCommands: 4,
    requiredKinds: ['repeat', 'collect'],
    requiredCommandMessage: '这关要用重复收集三颗星。',
    optimalSteps: 7,
    starThresholds: { threeStarsMaxSteps: 7, twoStarsMaxSteps: 8, oneStarMaxSteps: 9 },
    sampleProgram: [
      {
        id: 'sample-repeat',
        kind: 'repeat',
        params: { n: 3 },
        body: [
          { id: 'sample-repeat:body.0', kind: 'forward' },
          { id: 'sample-repeat:body.1', kind: 'collect' },
        ],
      },
      { id: 'sample-1', kind: 'forward' },
    ],
  },
  {
    id: 'jump-canyon-turn',
    title: '跳过峡谷',
    concept: '跳跃转向',
    worldId: 'canyon',
    difficultyStars: 4,
    conceptTags: ['jump', 'turnLeft', 'forward'],
    prompt: '跳过两块石头，再往上走到终点。',
    guide: '跳跃只会向前跳两格，转向后再继续前进。',
    successVoice: '峡谷跳跃完成。',
    hintVoice: '先跳两次，再左转往上走。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 4, y: 2 },
    obstacles: [
      { x: 1, y: 4 },
      { x: 3, y: 4 },
    ],
    allowedCommands: ['jump', 'turnLeft', 'forward'],
    maxCommands: 6,
    requiredKinds: ['jump'],
    requiredCommandMessage: '这关要用跳跃越过石头。',
    optimalSteps: 5,
    starThresholds: { threeStarsMaxSteps: 5, twoStarsMaxSteps: 6, oneStarMaxSteps: 7 },
    sampleProgram: [
      { id: 'sample-0', kind: 'jump' },
      { id: 'sample-1', kind: 'jump' },
      { id: 'sample-2', kind: 'turnLeft' },
      { id: 'sample-3', kind: 'forward' },
      { id: 'sample-4', kind: 'forward' },
    ],
  },
  {
    id: 'jump-collect-star',
    title: '跳到星星上',
    concept: '跳跃收集',
    worldId: 'canyon',
    difficultyStars: 4,
    conceptTags: ['jump', 'collect', 'forward'],
    prompt: '先跳过石头落到星星上，再收集。',
    guide: '跳跃的落点也可以放着能量星。',
    successVoice: '跳跃后准确收集。',
    hintVoice: '跳过去以后，小满会站在星星格子上。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 4, y: 4 },
    obstacles: [{ x: 1, y: 4 }],
    gems: [{ x: 2, y: 4 }],
    requiresAllGems: true,
    allowedCommands: ['jump', 'collect', 'forward'],
    maxCommands: 5,
    requiredKinds: ['jump', 'collect'],
    requiredCommandMessage: '这关要先跳跃，再收集星星。',
    optimalSteps: 4,
    starThresholds: { threeStarsMaxSteps: 4, twoStarsMaxSteps: 5, oneStarMaxSteps: 6 },
    sampleProgram: [
      { id: 'sample-0', kind: 'jump' },
      { id: 'sample-1', kind: 'collect' },
      { id: 'sample-2', kind: 'forward' },
      { id: 'sample-3', kind: 'forward' },
    ],
  },
  {
    id: 'ifpath-jump-gate',
    title: '挡路就跳',
    concept: '条件跳跃',
    worldId: 'canyon',
    difficultyStars: 4,
    conceptTags: ['ifPath', 'jump', 'turnLeft', 'forward'],
    prompt: '前面被石头挡住时，用条件决定跳过去。',
    guide: '如果没路，可以在否分支放跳跃。',
    successVoice: '小满会判断什么时候该跳了。',
    hintVoice: '开头前面没路，否分支试试跳跃。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 2, y: 3 },
    obstacles: [{ x: 1, y: 4 }],
    allowedCommands: ['ifPath', 'jump', 'turnLeft', 'forward'],
    maxCommands: 5,
    requiredKinds: ['ifPath', 'jump'],
    requiredCommandMessage: '这关要用条件和跳跃。',
    optimalSteps: 3,
    starThresholds: { threeStarsMaxSteps: 3, twoStarsMaxSteps: 4, oneStarMaxSteps: 5 },
    sampleProgram: [
      {
        id: 'sample-ifpath',
        kind: 'ifPath',
        branchTrue: [{ id: 'sample-ifpath:true.0', kind: 'forward' }],
        branchFalse: [{ id: 'sample-ifpath:false.0', kind: 'jump' }],
      },
      { id: 'sample-1', kind: 'turnLeft' },
      { id: 'sample-2', kind: 'forward' },
    ],
  },
  {
    id: 'repeat-jump-canyon',
    title: '重复跳跃',
    concept: '重复跳跃',
    worldId: 'canyon',
    difficultyStars: 4,
    conceptTags: ['repeat', 'jump'],
    prompt: '两次跳跃完全一样，用重复块完成。',
    guide: '跳跃也能放进重复块里。',
    successVoice: '重复跳跃成功。',
    hintVoice: '把跳跃放进重复块，重复两次。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 4, y: 4 },
    obstacles: [
      { x: 1, y: 4 },
      { x: 3, y: 4 },
    ],
    allowedCommands: ['repeat', 'jump'],
    maxCommands: 3,
    requiredKinds: ['repeat', 'jump'],
    requiredCommandMessage: '这关要用重复跳跃。',
    optimalSteps: 2,
    starThresholds: { threeStarsMaxSteps: 2, twoStarsMaxSteps: 3, oneStarMaxSteps: 4 },
    sampleProgram: [
      {
        id: 'sample-repeat',
        kind: 'repeat',
        params: { n: 2 },
        body: [{ id: 'sample-repeat:body.0', kind: 'jump' }],
      },
    ],
  },
  {
    id: 'canyon-boss',
    title: '峡谷终点挑战',
    concept: '跳跃挑战',
    worldId: 'canyon',
    difficultyStars: 5,
    conceptTags: ['jump', 'collect', 'turnLeft', 'forward'],
    isBoss: true,
    prompt: '跳过石头、收好星星，再爬到终点。',
    guide: '这关把跳跃、收集和转向放在一起。',
    successVoice: '峡谷挑战完成。',
    hintVoice: '跳到星星上收集，然后继续走到右上角。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 4, y: 2 },
    obstacles: [{ x: 1, y: 4 }],
    gems: [{ x: 2, y: 4 }],
    requiresAllGems: true,
    allowedCommands: ['jump', 'collect', 'forward', 'turnLeft'],
    maxCommands: 7,
    requiredKinds: ['jump', 'collect'],
    requiredCommandMessage: '这关要先跳跃收星，再转向到终点。',
    optimalSteps: 6,
    starThresholds: { threeStarsMaxSteps: 6, twoStarsMaxSteps: 7, oneStarMaxSteps: 8 },
    sampleProgram: [
      { id: 'sample-0', kind: 'jump' },
      { id: 'sample-1', kind: 'collect' },
      { id: 'sample-2', kind: 'forward' },
      { id: 'sample-3', kind: 'forward' },
      { id: 'sample-4', kind: 'turnLeft' },
      { id: 'sample-5', kind: 'forward' },
      { id: 'sample-6', kind: 'forward' },
    ],
  },
  {
    id: 'procedure-long-road',
    title: '长路小卡',
    concept: '过程复用',
    worldId: 'tower',
    difficultyStars: 4,
    conceptTags: ['procCall', 'forward'],
    prompt: '调用预设小路卡，完成一条长直路。',
    guide: '过程可以把一段路线提前保存好。',
    successVoice: '小路卡运行完成。',
    hintVoice: '调用小路会执行预设的四步前进。',
    start: { x: 0, y: 0 },
    direction: 'east',
    target: { x: 4, y: 0 },
    obstacles: [],
    allowedCommands: ['procCall', 'forward'],
    maxCommands: 3,
    requiredKinds: ['procCall'],
    requiredCommandMessage: '这关要调用预设小路。',
    procedures: {
      helper: [
        { id: 'helper-0', kind: 'forward' },
        { id: 'helper-1', kind: 'forward' },
        { id: 'helper-2', kind: 'forward' },
        { id: 'helper-3', kind: 'forward' },
      ],
    },
    defaultProcedureId: 'helper',
    optimalSteps: 4,
    starThresholds: { threeStarsMaxSteps: 4, twoStarsMaxSteps: 5, oneStarMaxSteps: 6 },
    sampleProgram: [
      { id: 'sample-proc', kind: 'procCall', params: { procedureId: 'helper' } },
    ],
  },
  {
    id: 'procedure-repeat-road',
    title: '重复调用',
    concept: '过程与重复',
    worldId: 'tower',
    difficultyStars: 4,
    conceptTags: ['repeat', 'procCall', 'forward'],
    prompt: '把小路卡调用两次，走完整条通道。',
    guide: '过程调用也可以放进重复块。',
    successVoice: '你重复调用了同一张小路卡。',
    hintVoice: '把调用小路放进重复块里。',
    start: { x: 0, y: 0 },
    direction: 'east',
    target: { x: 4, y: 0 },
    obstacles: [],
    allowedCommands: ['repeat', 'procCall'],
    maxCommands: 3,
    requiredKinds: ['repeat', 'procCall'],
    requiredCommandMessage: '这关要重复调用小路。',
    procedures: {
      helper: [
        { id: 'helper-0', kind: 'forward' },
        { id: 'helper-1', kind: 'forward' },
      ],
    },
    defaultProcedureId: 'helper',
    optimalSteps: 4,
    starThresholds: { threeStarsMaxSteps: 4, twoStarsMaxSteps: 5, oneStarMaxSteps: 6 },
    sampleProgram: [
      {
        id: 'sample-repeat',
        kind: 'repeat',
        params: { n: 2 },
        body: [{ id: 'sample-repeat:body.0', kind: 'procCall', params: { procedureId: 'helper' } }],
      },
    ],
  },
  {
    id: 'procedure-star-stairs',
    title: '小路带星星',
    concept: '过程收集',
    worldId: 'tower',
    difficultyStars: 5,
    conceptTags: ['procCall', 'collect', 'turnLeft', 'forward'],
    prompt: '调用一张会收星星的小路卡。',
    guide: '过程里面也能包含收集动作。',
    successVoice: '小路卡帮小满收到了星星。',
    hintVoice: '这张预设小路已经包含收集。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 2, y: 2 },
    obstacles: [],
    gems: [{ x: 1, y: 4 }],
    requiresAllGems: true,
    allowedCommands: ['procCall', 'forward', 'collect'],
    maxCommands: 3,
    requiredKinds: ['procCall'],
    requiredCommandMessage: '这关要调用包含收集动作的小路。',
    procedures: {
      helper: [
        { id: 'helper-0', kind: 'forward' },
        { id: 'helper-1', kind: 'collect' },
        { id: 'helper-2', kind: 'forward' },
        { id: 'helper-3', kind: 'turnLeft' },
        { id: 'helper-4', kind: 'forward' },
        { id: 'helper-5', kind: 'forward' },
      ],
    },
    defaultProcedureId: 'helper',
    optimalSteps: 6,
    starThresholds: { threeStarsMaxSteps: 6, twoStarsMaxSteps: 7, oneStarMaxSteps: 8 },
    sampleProgram: [
      { id: 'sample-proc', kind: 'procCall', params: { procedureId: 'helper' } },
    ],
  },
  {
    id: 'procedure-while-tower',
    title: '小路进循环',
    concept: '过程循环',
    worldId: 'tower',
    difficultyStars: 5,
    conceptTags: ['whileNotGoal', 'procCall', 'forward'],
    prompt: '循环调用小路卡，直到走到终点。',
    guide: '每次调用小路卡都会走一小段，循环会继续检查终点。',
    successVoice: '过程和循环配合起来了。',
    hintVoice: '把调用小路放进“直到终点”里面。',
    start: { x: 0, y: 0 },
    direction: 'east',
    target: { x: 4, y: 0 },
    obstacles: [],
    allowedCommands: ['whileNotGoal', 'procCall'],
    maxCommands: 3,
    requiredKinds: ['whileNotGoal', 'procCall'],
    requiredCommandMessage: '这关要循环调用小路。',
    procedures: {
      helper: [{ id: 'helper-0', kind: 'forward' }],
    },
    defaultProcedureId: 'helper',
    optimalSteps: 4,
    starThresholds: { threeStarsMaxSteps: 4, twoStarsMaxSteps: 5, oneStarMaxSteps: 6 },
    sampleProgram: [
      {
        id: 'sample-while',
        kind: 'whileNotGoal',
        body: [{ id: 'sample-while:body.0', kind: 'procCall', params: { procedureId: 'helper' } }],
      },
    ],
  },
  {
    id: 'tower-boss',
    title: '编程塔挑战',
    concept: '综合挑战',
    worldId: 'tower',
    difficultyStars: 5,
    conceptTags: ['procCall', 'turnLeft', 'forward'],
    isBoss: true,
    prompt: '调用完整小路卡，从塔底走到塔顶。',
    guide: '最后一关把过程当成完整路线来使用。',
    successVoice: '编程塔登顶成功。',
    hintVoice: '调用小路卡，它已经保存了塔里的完整路线。',
    start: { x: 0, y: 4 },
    direction: 'east',
    target: { x: 4, y: 0 },
    obstacles: [],
    allowedCommands: ['procCall', 'forward', 'turnLeft'],
    maxCommands: 3,
    requiredKinds: ['procCall'],
    requiredCommandMessage: '这关要调用最终小路卡。',
    procedures: {
      helper: [
        { id: 'helper-0', kind: 'forward' },
        { id: 'helper-1', kind: 'forward' },
        { id: 'helper-2', kind: 'forward' },
        { id: 'helper-3', kind: 'forward' },
        { id: 'helper-4', kind: 'turnLeft' },
        { id: 'helper-5', kind: 'forward' },
        { id: 'helper-6', kind: 'forward' },
        { id: 'helper-7', kind: 'forward' },
        { id: 'helper-8', kind: 'forward' },
      ],
    },
    defaultProcedureId: 'helper',
    optimalSteps: 9,
    starThresholds: { threeStarsMaxSteps: 9, twoStarsMaxSteps: 10, oneStarMaxSteps: 11 },
    sampleProgram: [
      { id: 'sample-proc', kind: 'procCall', params: { procedureId: 'helper' } },
    ],
  },
];
