import type { GoldenSetItem } from './types';

const NOW = 1_712_000_000_000;

export const GOLDEN_SET_SEED: GoldenSetItem[] = [
  {
    id: 'gs_diag_numberline_001',
    version: 1,
    status: 'published',
    skeleton: {
      skill: 'numberLineDistance',
      secondarySkills: ['countingTo10'],
      difficulty: -1.1,
      bloomLevel: 'apply',
      expectedAccuracy: 0.72,
    },
    content: {
      prompt: '小松鼠从 2 跳到 5，要跳几步？',
      narration: '小松鼠从二跳到五，要跳几步呢？',
      inputType: 'choice',
      correctAnswer: 3,
      choices: [
        { text: '3', value: 3, isCorrect: true, trapType: 'none' },
        { text: '2', value: 2, isCorrect: false, trapType: 'partial' },
        { text: '4', value: 4, isCorrect: false, trapType: 'off-one' },
        { text: '5', value: 5, isCorrect: false, trapType: 'swap-op' },
      ],
      solutionSteps: ['从 2 接着数到 5', '3, 4, 5，一共跳了 3 步'],
    },
    presentation: {
      variant: 'numberLine',
      level: 2,
      expression: '2 -> 5',
      objects: ['⭐', '⭐', '⭐'],
      numberLine: { start: 2, end: 5 },
      theme: { emoji: '⭐', colorHint: 'amber' },
      barModel: [2, 3],
      scaffoldText: '先找到起点，再一格一格往前跳。',
      principleText: '从 2 跳到 5，要数一数中间一共前进了几格。',
    },
    context: {
      scene: 'forest',
      actors: ['小松鼠'],
      emotion: 'curious',
    },
    meta: {
      authorId: 'seed-expert',
      authorRole: 'expert',
      reviewerId: 'seed-reviewer',
      reviewedAt: NOW,
      source: 'handcraft',
      tags: ['diagnostic', 'milestone', 'number-line'],
      usedInCount: 0,
      globalAccuracy: 0,
    },
    safety: {
      reviewedForBias: true,
      reviewedForSafety: true,
      safetyFlags: [],
    },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gs_diag_compare_001',
    version: 1,
    status: 'published',
    skeleton: {
      skill: 'compareWithin5',
      secondarySkills: ['visualMatching'],
      difficulty: -1.6,
      bloomLevel: 'understand',
      expectedAccuracy: 0.8,
    },
    content: {
      prompt: '5 个草莓和 3 个草莓，哪个更多？',
      narration: '五个草莓和三个草莓，哪个更多？',
      inputType: 'choice',
      correctAnswer: 5,
      choices: [
        { text: '5', value: 5, isCorrect: true, trapType: 'none' },
        { text: '3', value: 3, isCorrect: false, trapType: 'swap-op' },
        { text: '2', value: 2, isCorrect: false, trapType: 'partial' },
        { text: '4', value: 4, isCorrect: false, trapType: 'off-one' },
      ],
      solutionSteps: ['先看一边有几个', '5 比 3 大，所以 5 更多'],
    },
    presentation: {
      variant: 'compare',
      level: 1,
      expression: '5 ? 3',
      objects: ['🍓', '🍓', '🍓', '🍓', '🍓'],
      comparePair: { left: 5, right: 3 },
      theme: { emoji: '🍓', colorHint: 'pink' },
      barModel: [5, 3],
      scaffoldText: '先数左边，再数右边，看看谁更多。',
      principleText: '比较大小时，数量更多的一边就是更大的数。',
    },
    context: {
      scene: 'garden',
      actors: ['小兔'],
      emotion: 'calm',
    },
    meta: {
      authorId: 'seed-expert',
      authorRole: 'expert',
      reviewerId: 'seed-reviewer',
      reviewedAt: NOW,
      source: 'handcraft',
      tags: ['diagnostic', 'milestone', 'compare'],
      usedInCount: 0,
      globalAccuracy: 0,
    },
    safety: {
      reviewedForBias: true,
      reviewedForSafety: true,
      safetyFlags: [],
    },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gs_diag_maketen_001',
    version: 1,
    status: 'published',
    skeleton: {
      skill: 'makeTen',
      secondarySkills: ['addWithin10'],
      difficulty: -0.2,
      bloomLevel: 'apply',
      expectedAccuracy: 0.68,
    },
    content: {
      prompt: '小熊已经有 6 个气球，还差几个就到 10 个？',
      narration: '小熊已经有六个气球，还差几个就到十个？',
      inputType: 'choice',
      correctAnswer: 4,
      choices: [
        { text: '4', value: 4, isCorrect: true, trapType: 'none' },
        { text: '6', value: 6, isCorrect: false, trapType: 'swap-op' },
        { text: '3', value: 3, isCorrect: false, trapType: 'off-one' },
        { text: '5', value: 5, isCorrect: false, trapType: 'off-one' },
      ],
      solutionSteps: ['先想 6 再加几变成 10', '6 加 4 等于 10'],
    },
    presentation: {
      variant: 'makeTen',
      level: 3,
      expression: '6 + ? = 10',
      objects: ['🎈', '🎈', '🎈', '🎈', '🎈', '🎈'],
      theme: { emoji: '🎈', colorHint: 'pink' },
      barModel: [6, 4],
      scaffoldText: '先把 10 想成一个完整小队，再看还差几位。',
      principleText: '凑十时，想“已有多少，还差多少”会更快。',
    },
    context: {
      scene: 'party',
      actors: ['小熊'],
      emotion: 'joyful',
    },
    meta: {
      authorId: 'seed-expert',
      authorRole: 'expert',
      reviewerId: 'seed-reviewer',
      reviewedAt: NOW,
      source: 'handcraft',
      tags: ['diagnostic', 'milestone', 'make-ten'],
      usedInCount: 0,
      globalAccuracy: 0,
    },
    safety: {
      reviewedForBias: true,
      reviewedForSafety: true,
      safetyFlags: [],
    },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gs_story_daily_001',
    version: 1,
    status: 'published',
    skeleton: {
      skill: 'storyAddition',
      secondarySkills: ['addWithin10'],
      difficulty: -0.1,
      bloomLevel: 'apply',
      expectedAccuracy: 0.76,
    },
    content: {
      prompt: '小熊烤了 3 个饼干，妈妈又烤了 4 个，一共有几个？',
      narration: '小熊烤了三个饼干，妈妈又烤了四个，一共有几个？',
      inputType: 'choice',
      correctAnswer: 7,
      choices: [
        { text: '7', value: 7, isCorrect: true, trapType: 'none' },
        { text: '1', value: 1, isCorrect: false, trapType: 'swap-op' },
        { text: '4', value: 4, isCorrect: false, trapType: 'partial' },
        { text: '8', value: 8, isCorrect: false, trapType: 'off-one' },
      ],
      solutionSteps: ['先数 3 个', '再接着数 4 个，一共是 7 个'],
    },
    presentation: {
      variant: 'story',
      level: 2,
      expression: '3 + 4 = ?',
      objects: ['🍪', '🍪', '🍪', '🍪', '🍪', '🍪', '🍪'],
      theme: { emoji: '🍪', colorHint: 'orange' },
      barModel: [3, 4],
      scaffoldText: '把前后两次烤好的饼干合在一起数。',
      principleText: '故事题里“又来了多少”通常是在原来基础上继续加。',
    },
    context: {
      scene: 'kitchen',
      actors: ['小熊', '妈妈'],
      emotion: 'joyful',
    },
    meta: {
      authorId: 'seed-expert',
      authorRole: 'expert',
      reviewerId: 'seed-reviewer',
      reviewedAt: NOW,
      source: 'handcraft',
      tags: ['story', 'daily', 'golden'],
      usedInCount: 0,
      globalAccuracy: 0,
    },
    safety: {
      reviewedForBias: true,
      reviewedForSafety: true,
      safetyFlags: [],
    },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gs_festival_spring_001',
    version: 1,
    status: 'published',
    skeleton: {
      skill: 'storyAddition',
      secondarySkills: ['addWithin10'],
      difficulty: 0.4,
      bloomLevel: 'apply',
      expectedAccuracy: 0.66,
    },
    content: {
      prompt: '过春节时，盘子里有 4 个汤圆，又放上 5 个，一共有几个？',
      narration: '过春节时，盘子里有四个汤圆，又放上五个，一共有几个？',
      inputType: 'choice',
      correctAnswer: 9,
      choices: [
        { text: '9', value: 9, isCorrect: true, trapType: 'none' },
        { text: '1', value: 1, isCorrect: false, trapType: 'swap-op' },
        { text: '5', value: 5, isCorrect: false, trapType: 'partial' },
        { text: '10', value: 10, isCorrect: false, trapType: 'off-one' },
      ],
      solutionSteps: ['先看原来有 4 个', '再把新放的 5 个加进去'],
    },
    presentation: {
      variant: 'story',
      level: 3,
      expression: '4 + 5 = ?',
      objects: ['🥣', '🥣', '🥣', '🥣', '🥣', '🥣', '🥣', '🥣', '🥣'],
      theme: { emoji: '🥣', colorHint: 'orange' },
      barModel: [4, 5],
      scaffoldText: '节日里的食物也可以帮我们一起数一数。',
      principleText: '把前后两部分合起来，就是总数。',
    },
    context: {
      scene: 'festival',
      actors: ['小满一家'],
      festival: 'spring-fes',
      emotion: 'joyful',
    },
    meta: {
      authorId: 'seed-expert',
      authorRole: 'expert',
      reviewerId: 'seed-reviewer',
      reviewedAt: NOW,
      source: 'handcraft',
      tags: ['story', 'festival', 'spring-fes'],
      usedInCount: 0,
      globalAccuracy: 0,
    },
    safety: {
      reviewedForBias: true,
      reviewedForSafety: true,
      safetyFlags: [],
    },
    createdAt: NOW,
    updatedAt: NOW,
  },
];
