import type { LearningCard } from '../learningCards/types';

export type EnglishItem = LearningCard;

export const ENGLISH_ITEMS: EnglishItem[] = [
  {
    id: 'a-apple',
    glyph: 'Aa',
    title: 'Apple',
    phonetic: '/ˈæpəl/',
    graphic: '🍎',
    imageLabel: 'apple',
    words: [
      { text: 'apple', phonetic: '/ˈæpəl/' },
      { text: 'ant', phonetic: '/ænt/' },
      { text: 'arm', phonetic: '/ɑːrm/' },
    ],
    sentence: 'A is for apple.',
    tone: 'from-rose-100 via-orange-100 to-lime-100',
  },
  {
    id: 'b-ball',
    glyph: 'Bb',
    title: 'Ball',
    phonetic: '/bɔːl/',
    graphic: '⚽',
    imageLabel: 'ball',
    words: [
      { text: 'ball', phonetic: '/bɔːl/' },
      { text: 'book', phonetic: '/bʊk/' },
      { text: 'baby', phonetic: '/ˈbeɪbi/' },
    ],
    sentence: 'B is for ball.',
    tone: 'from-sky-100 via-cyan-100 to-emerald-100',
  },
  {
    id: 'c-cat',
    glyph: 'Cc',
    title: 'Cat',
    phonetic: '/kæt/',
    graphic: '🐱',
    imageLabel: 'cat',
    words: [
      { text: 'cat', phonetic: '/kæt/' },
      { text: 'cup', phonetic: '/kʌp/' },
      { text: 'cake', phonetic: '/keɪk/' },
    ],
    sentence: 'C is for cat.',
    tone: 'from-yellow-100 via-lime-100 to-emerald-100',
  },
  {
    id: 'd-dog',
    glyph: 'Dd',
    title: 'Dog',
    phonetic: '/dɔːɡ/',
    graphic: '🐶',
    imageLabel: 'dog',
    words: [
      { text: 'dog', phonetic: '/dɔːɡ/' },
      { text: 'door', phonetic: '/dɔːr/' },
      { text: 'duck', phonetic: '/dʌk/' },
    ],
    sentence: 'D is for dog.',
    tone: 'from-amber-100 via-orange-100 to-yellow-100',
  },
  {
    id: 'e-egg',
    glyph: 'Ee',
    title: 'Egg',
    phonetic: '/eɡ/',
    graphic: '🥚',
    imageLabel: 'egg',
    words: [
      { text: 'egg', phonetic: '/eɡ/' },
      { text: 'ear', phonetic: '/ɪr/' },
      { text: 'eye', phonetic: '/aɪ/' },
    ],
    sentence: 'E is for egg.',
    tone: 'from-stone-100 via-yellow-100 to-lime-100',
  },
  {
    id: 'f-fish',
    glyph: 'Ff',
    title: 'Fish',
    phonetic: '/fɪʃ/',
    graphic: '🐟',
    imageLabel: 'fish',
    words: [
      { text: 'fish', phonetic: '/fɪʃ/' },
      { text: 'face', phonetic: '/feɪs/' },
      { text: 'five', phonetic: '/faɪv/' },
    ],
    sentence: 'F is for fish.',
    tone: 'from-cyan-100 via-sky-100 to-indigo-100',
  },
  {
    id: 'g-grape',
    glyph: 'Gg',
    title: 'Grape',
    phonetic: '/ɡreɪp/',
    graphic: '🍇',
    imageLabel: 'grape',
    words: [
      { text: 'grape', phonetic: '/ɡreɪp/' },
      { text: 'green', phonetic: '/ɡriːn/' },
      { text: 'girl', phonetic: '/ɡɜːrl/' },
    ],
    sentence: 'G is for grape.',
    tone: 'from-violet-100 via-purple-100 to-lime-100',
  },
  {
    id: 'h-house',
    glyph: 'Hh',
    title: 'House',
    phonetic: '/haʊs/',
    graphic: '🏠',
    imageLabel: 'house',
    words: [
      { text: 'house', phonetic: '/haʊs/' },
      { text: 'hand', phonetic: '/hænd/' },
      { text: 'hat', phonetic: '/hæt/' },
    ],
    sentence: 'H is for house.',
    tone: 'from-emerald-100 via-lime-100 to-yellow-100',
  },
  {
    id: 'i-ice-cream',
    glyph: 'Ii',
    title: 'Ice cream',
    phonetic: '/ˈaɪs kriːm/',
    graphic: '🍦',
    imageLabel: 'ice cream',
    words: [
      { text: 'ice', phonetic: '/aɪs/' },
      { text: 'in', phonetic: '/ɪn/' },
      { text: 'ink', phonetic: '/ɪŋk/' },
    ],
    sentence: 'I is for ice cream.',
    tone: 'from-pink-100 via-sky-100 to-cyan-100',
  },
  {
    id: 'j-juice',
    glyph: 'Jj',
    title: 'Juice',
    phonetic: '/dʒuːs/',
    graphic: '🧃',
    imageLabel: 'juice',
    words: [
      { text: 'juice', phonetic: '/dʒuːs/' },
      { text: 'jump', phonetic: '/dʒʌmp/' },
      { text: 'jam', phonetic: '/dʒæm/' },
    ],
    sentence: 'J is for juice.',
    tone: 'from-orange-100 via-rose-100 to-pink-100',
  },
  {
    id: 'k-kite',
    glyph: 'Kk',
    title: 'Kite',
    phonetic: '/kaɪt/',
    graphic: '🪁',
    imageLabel: 'kite',
    words: [
      { text: 'kite', phonetic: '/kaɪt/' },
      { text: 'key', phonetic: '/kiː/' },
      { text: 'kid', phonetic: '/kɪd/' },
    ],
    sentence: 'K is for kite.',
    tone: 'from-teal-100 via-sky-100 to-yellow-100',
  },
  {
    id: 'l-lion',
    glyph: 'Ll',
    title: 'Lion',
    phonetic: '/ˈlaɪən/',
    graphic: '🦁',
    imageLabel: 'lion',
    words: [
      { text: 'lion', phonetic: '/ˈlaɪən/' },
      { text: 'leaf', phonetic: '/liːf/' },
      { text: 'leg', phonetic: '/leɡ/' },
    ],
    sentence: 'L is for lion.',
    tone: 'from-amber-100 via-yellow-100 to-emerald-100',
  },
];

export const DEFAULT_ENGLISH_ITEM = ENGLISH_ITEMS[0];

export function findEnglishItemById(id: string | null | undefined) {
  return ENGLISH_ITEMS.find((item) => item.id === id) ?? null;
}
