import type { LearningCard } from '../learningCards/types';

export type EnglishItem = LearningCard;

export const ENGLISH_ITEMS: EnglishItem[] = [
  {
    id: 'a-apple',
    glyph: 'Aa',
    title: 'Apple',
    phonetic: '/ˈæpəl/',
    graphic: '🍎',
    imageLabel: 'apple',
    words: [
      { text: 'apple', phonetic: '/ˈæpəl/' },
      { text: 'ant', phonetic: '/ænt/' },
      { text: 'arm', phonetic: '/ɑːrm/' },
    ],
    sentence: 'A is for apple.',
    tone: 'from-rose-100 via-orange-100 to-lime-100',
  },
  {
    id: 'b-ball',
    glyph: 'Bb',
    title: 'Ball',
    phonetic: '/bɔːl/',
    graphic: '⚽',
    imageLabel: 'ball',
    words: [
      { text: 'ball', phonetic: '/bɔːl/' },
      { text: 'book', phonetic: '/bʊk/' },
      { text: 'baby', phonetic: '/ˈbeɪbi/' },
    ],
    sentence: 'B is for ball.',
    tone: 'from-sky-100 via-cyan-100 to-emerald-100',
  },
  {
    id: 'c-cat',
    glyph: 'Cc',
    title: 'Cat',
    phonetic: '/kæt/',
    graphic: '🐱',
    imageLabel: 'cat',
    words: [
      { text: 'cat', phonetic: '/kæt/' },
      { text: 'cup', phonetic: '/kʌp/' },
      { text: 'cake', phonetic: '/keɪk/' },
    ],
    sentence: 'C is for cat.',
    tone: 'from-yellow-100 via-lime-100 to-emerald-100',
  },
  {
    id: 'd-dog',
    glyph: 'Dd',
    title: 'Dog',
    phonetic: '/dɔːɡ/',
    graphic: '🐶',
    imageLabel: 'dog',
    words: [
      { text: 'dog', phonetic: '/dɔːɡ/' },
      { text: 'door', phonetic: '/dɔːr/' },
      { text: 'duck', phonetic: '/dʌk/' },
    ],
    sentence: 'D is for dog.',
    tone: 'from-amber-100 via-orange-100 to-yellow-100',
  },
  {
    id: 'e-egg',
    glyph: 'Ee',
    title: 'Egg',
    phonetic: '/eɡ/',
    graphic: '🥚',
    imageLabel: 'egg',
    words: [
      { text: 'egg', phonetic: '/eɡ/' },
      { text: 'ear', phonetic: '/ɪr/' },
      { text: 'eye', phonetic: '/aɪ/' },
    ],
    sentence: 'E is for egg.',
    tone: 'from-stone-100 via-yellow-100 to-lime-100',
  },
  {
    id: 'f-fish',
    glyph: 'Ff',
    title: 'Fish',
    phonetic: '/fɪʃ/',
    graphic: '🐟',
    imageLabel: 'fish',
    words: [
      { text: 'fish', phonetic: '/fɪʃ/' },
      { text: 'face', phonetic: '/feɪs/' },
      { text: 'five', phonetic: '/faɪv/' },
    ],
    sentence: 'F is for fish.',
    tone: 'from-cyan-100 via-sky-100 to-indigo-100',
  },
  {
    id: 'g-grape',
    glyph: 'Gg',
    title: 'Grape',
    phonetic: '/ɡreɪp/',
    graphic: '🍇',
    imageLabel: 'grape',
    words: [
      { text: 'grape', phonetic: '/ɡreɪp/' },
      { text: 'green', phonetic: '/ɡriːn/' },
      { text: 'girl', phonetic: '/ɡɜːrl/' },
    ],
    sentence: 'G is for grape.',
    tone: 'from-violet-100 via-purple-100 to-lime-100',
  },
  {
    id: 'h-house',
    glyph: 'Hh',
    title: 'House',
    phonetic: '/haʊs/',
    graphic: '🏠',
    imageLabel: 'house',
    words: [
      { text: 'house', phonetic: '/haʊs/' },
      { text: 'hand', phonetic: '/hænd/' },
      { text: 'hat', phonetic: '/hæt/' },
    ],
    sentence: 'H is for house.',
    tone: 'from-emerald-100 via-lime-100 to-yellow-100',
  },
  {
    id: 'i-ice-cream',
    glyph: 'Ii',
    title: 'Ice cream',
    phonetic: '/ˈaɪs kriːm/',
    graphic: '🍦',
    imageLabel: 'ice cream',
    words: [
      { text: 'ice', phonetic: '/aɪs/' },
      { text: 'in', phonetic: '/ɪn/' },
      { text: 'ink', phonetic: '/ɪŋk/' },
    ],
    sentence: 'I is for ice cream.',
    tone: 'from-pink-100 via-sky-100 to-cyan-100',
  },
  {
    id: 'j-juice',
    glyph: 'Jj',
    title: 'Juice',
    phonetic: '/dʒuːs/',
    graphic: '🧃',
    imageLabel: 'juice',
    words: [
      { text: 'juice', phonetic: '/dʒuːs/' },
      { text: 'jump', phonetic: '/dʒʌmp/' },
      { text: 'jam', phonetic: '/dʒæm/' },
    ],
    sentence: 'J is for juice.',
    tone: 'from-orange-100 via-rose-100 to-pink-100',
  },
  {
    id: 'k-kite',
    glyph: 'Kk',
    title: 'Kite',
    phonetic: '/kaɪt/',
    graphic: '🪁',
    imageLabel: 'kite',
    words: [
      { text: 'kite', phonetic: '/kaɪt/' },
      { text: 'key', phonetic: '/kiː/' },
      { text: 'kid', phonetic: '/kɪd/' },
    ],
    sentence: 'K is for kite.',
    tone: 'from-teal-100 via-sky-100 to-yellow-100',
  },
  {
    id: 'l-lion',
    glyph: 'Ll',
    title: 'Lion',
    phonetic: '/ˈlaɪən/',
    graphic: '🦁',
    imageLabel: 'lion',
    words: [
      { text: 'lion', phonetic: '/ˈlaɪən/' },
      { text: 'leaf', phonetic: '/liːf/' },
      { text: 'leg', phonetic: '/leɡ/' },
    ],
    sentence: 'L is for lion.',
    tone: 'from-amber-100 via-yellow-100 to-emerald-100',
  },
  {
    id: 'm-moon',
    glyph: 'Mm',
    title: 'Moon',
    phonetic: '/muːn/',
    graphic: '🌙',
    imageLabel: 'moon',
    words: [
      { text: 'moon', phonetic: '/muːn/' },
      { text: 'milk', phonetic: '/mɪlk/' },
      { text: 'map', phonetic: '/mæp/' },
    ],
    sentence: 'M is for moon.',
    tone: 'from-indigo-100 via-sky-100 to-cyan-100',
  },
  {
    id: 'n-nest',
    glyph: 'Nn',
    title: 'Nest',
    phonetic: '/nest/',
    graphic: '🪺',
    imageLabel: 'nest',
    words: [
      { text: 'nest', phonetic: '/nest/' },
      { text: 'nose', phonetic: '/noʊz/' },
      { text: 'nine', phonetic: '/naɪn/' },
    ],
    sentence: 'N is for nest.',
    tone: 'from-amber-100 via-lime-100 to-emerald-100',
  },
  {
    id: 'o-orange',
    glyph: 'Oo',
    title: 'Orange',
    phonetic: '/ˈɔːrɪndʒ/',
    graphic: '🍊',
    imageLabel: 'orange',
    words: [
      { text: 'orange', phonetic: '/ˈɔːrɪndʒ/' },
      { text: 'octopus', phonetic: '/ˈɑːktəpəs/' },
      { text: 'open', phonetic: '/ˈoʊpən/' },
    ],
    sentence: 'O is for orange.',
    tone: 'from-orange-100 via-yellow-100 to-lime-100',
  },
  {
    id: 'p-panda',
    glyph: 'Pp',
    title: 'Panda',
    phonetic: '/ˈpændə/',
    graphic: '🐼',
    imageLabel: 'panda',
    words: [
      { text: 'panda', phonetic: '/ˈpændə/' },
      { text: 'pen', phonetic: '/pen/' },
      { text: 'pig', phonetic: '/pɪɡ/' },
    ],
    sentence: 'P is for panda.',
    tone: 'from-slate-100 via-lime-100 to-sky-100',
  },
  {
    id: 'q-queen',
    glyph: 'Qq',
    title: 'Queen',
    phonetic: '/kwiːn/',
    graphic: '👑',
    imageLabel: 'queen',
    words: [
      { text: 'queen', phonetic: '/kwiːn/' },
      { text: 'quiet', phonetic: '/ˈkwaɪət/' },
      { text: 'quilt', phonetic: '/kwɪlt/' },
    ],
    sentence: 'Q is for queen.',
    tone: 'from-yellow-100 via-amber-100 to-pink-100',
  },
  {
    id: 'r-rainbow',
    glyph: 'Rr',
    title: 'Rainbow',
    phonetic: '/ˈreɪnboʊ/',
    graphic: '🌈',
    imageLabel: 'rainbow',
    words: [
      { text: 'rainbow', phonetic: '/ˈreɪnboʊ/' },
      { text: 'red', phonetic: '/red/' },
      { text: 'run', phonetic: '/rʌn/' },
    ],
    sentence: 'R is for rainbow.',
    tone: 'from-rose-100 via-yellow-100 to-sky-100',
  },
  {
    id: 's-sun',
    glyph: 'Ss',
    title: 'Sun',
    phonetic: '/sʌn/',
    graphic: '☀️',
    imageLabel: 'sun',
    words: [
      { text: 'sun', phonetic: '/sʌn/' },
      { text: 'star', phonetic: '/stɑːr/' },
      { text: 'sock', phonetic: '/sɑːk/' },
    ],
    sentence: 'S is for sun.',
    tone: 'from-yellow-100 via-amber-100 to-lime-100',
  },
  {
    id: 't-tree',
    glyph: 'Tt',
    title: 'Tree',
    phonetic: '/triː/',
    graphic: '🌳',
    imageLabel: 'tree',
    words: [
      { text: 'tree', phonetic: '/triː/' },
      { text: 'toy', phonetic: '/tɔɪ/' },
      { text: 'ten', phonetic: '/ten/' },
    ],
    sentence: 'T is for tree.',
    tone: 'from-lime-100 via-green-100 to-emerald-100',
  },
  {
    id: 'u-umbrella',
    glyph: 'Uu',
    title: 'Umbrella',
    phonetic: '/ʌmˈbrelə/',
    graphic: '☂️',
    imageLabel: 'umbrella',
    words: [
      { text: 'umbrella', phonetic: '/ʌmˈbrelə/' },
      { text: 'up', phonetic: '/ʌp/' },
      { text: 'under', phonetic: '/ˈʌndər/' },
    ],
    sentence: 'U is for umbrella.',
    tone: 'from-violet-100 via-sky-100 to-cyan-100',
  },
  {
    id: 'v-van',
    glyph: 'Vv',
    title: 'Van',
    phonetic: '/væn/',
    graphic: '🚐',
    imageLabel: 'van',
    words: [
      { text: 'van', phonetic: '/væn/' },
      { text: 'vest', phonetic: '/vest/' },
      { text: 'violin', phonetic: '/ˌvaɪəˈlɪn/' },
    ],
    sentence: 'V is for van.',
    tone: 'from-orange-100 via-sky-100 to-emerald-100',
  },
  {
    id: 'w-whale',
    glyph: 'Ww',
    title: 'Whale',
    phonetic: '/weɪl/',
    graphic: '🐳',
    imageLabel: 'whale',
    words: [
      { text: 'whale', phonetic: '/weɪl/' },
      { text: 'water', phonetic: '/ˈwɔːtər/' },
      { text: 'window', phonetic: '/ˈwɪndoʊ/' },
    ],
    sentence: 'W is for whale.',
    tone: 'from-cyan-100 via-blue-100 to-indigo-100',
  },
  {
    id: 'x-xylophone',
    glyph: 'Xx',
    title: 'Xylophone',
    phonetic: '/ˈzaɪləfoʊn/',
    graphic: '🎼',
    imageLabel: 'xylophone',
    words: [
      { text: 'xylophone', phonetic: '/ˈzaɪləfoʊn/' },
      { text: 'fox', phonetic: '/fɑːks/' },
      { text: 'box', phonetic: '/bɑːks/' },
    ],
    sentence: 'X is for xylophone.',
    tone: 'from-pink-100 via-violet-100 to-sky-100',
  },
  {
    id: 'y-yoyo',
    glyph: 'Yy',
    title: 'Yo-yo',
    phonetic: '/ˈjoʊ joʊ/',
    graphic: '🪀',
    imageLabel: 'yo-yo',
    words: [
      { text: 'yo-yo', phonetic: '/ˈjoʊ joʊ/' },
      { text: 'yellow', phonetic: '/ˈjeloʊ/' },
      { text: 'yes', phonetic: '/jes/' },
    ],
    sentence: 'Y is for yo-yo.',
    tone: 'from-yellow-100 via-lime-100 to-sky-100',
  },
  {
    id: 'z-zebra',
    glyph: 'Zz',
    title: 'Zebra',
    phonetic: '/ˈziːbrə/',
    graphic: '🦓',
    imageLabel: 'zebra',
    words: [
      { text: 'zebra', phonetic: '/ˈziːbrə/' },
      { text: 'zero', phonetic: '/ˈzɪroʊ/' },
      { text: 'zoo', phonetic: '/zuː/' },
    ],
    sentence: 'Z is for zebra.',
    tone: 'from-slate-100 via-stone-100 to-lime-100',
  },
];

export const DEFAULT_ENGLISH_ITEM = ENGLISH_ITEMS[0];

export function findEnglishItemById(id: string | null | undefined) {
  return ENGLISH_ITEMS.find((item) => item.id === id) ?? null;
}
